import { Shield, Globe2, Terminal, Mail, Folder, Settings, FilePenLine } from 'lucide-react';
export const applications = [
  {
    id: 'root',
    name: 'Project Root',
    subtitle: '조사 관리',
    icon: Shield,
    asset: 'root',
    category: 'Office',
    width: 1040,
    height: 700,
  },
  {
    id: 'browser',
    name: 'Firefox',
    subtitle: '웹 브라우저',
    icon: Globe2,
    asset: 'firefox.png',
    category: 'Internet',
    width: 1120,
    height: 750,
  },
  {
    id: 'files',
    name: 'Dolphin',
    subtitle: '파일 관리자',
    icon: Folder,
    asset: 'files.svg',
    category: 'System',
    width: 940,
    height: 620,
  },
  {
    id: 'terminal',
    name: 'Konsole',
    subtitle: '터미널',
    icon: Terminal,
    asset: 'terminal.svg',
    category: 'System',
    width: 880,
    height: 570,
  },
  {
    id: 'mail',
    name: 'KMail',
    subtitle: '메일 클라이언트',
    icon: Mail,
    asset: 'mail.svg',
    category: 'Internet',
    width: 1100,
    height: 670,
  },
  {
    id: 'settings',
    name: '시스템 설정',
    subtitle: 'System Settings',
    icon: Settings,
    asset: 'settings.svg',
    category: 'System',
    width: 1060,
    height: 710,
  },
  {
    id: 'editor',
    name: 'KWrite',
    subtitle: '텍스트 편집기',
    icon: FilePenLine,
    asset: 'editor.svg',
    category: 'Office',
    width: 920,
    height: 660,
  },
] as const;
export type AppId = (typeof applications)[number]['id'];
